service: typescript-server-serverless

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  app:
    handler: dist/app.handler
    events:
    - http: ANY /
    - http: ANY /{proxy+}
